### ISSUE TITLE
How can i change style of button.

### ISSUE THREAD

**Issue by Thibault4** [juanjotorres90/ngx-material-intl-tel-input#19]
Hello i have set my custom button : 

`<ngx-material-intl-tel-input
														[autoIpLookup]="true" [enablePlaceholder]="false"
														[hidePhoneIcon]="true" [required]="true"
														[textLabels]="defaultTextLabels">
													</ngx-material-intl-tel-input>`
													
But how can i customize button color ? I have try to set ngStyle, style and other tips but nothing work.

Thanks

**Comment by juanjotorres90** [comment]
Hi,

These are some of the CSS variables you can override in your global styles to change the colors:

```scss
:root {
  @include mat.all-component-themes(m3-theme.$light-theme);

  & {
    --mdc-theme-primary: #209ffc;
    --mdc-theme-secondary: #023871;
    --mdc-theme-error: #f44336;
    --mdc-typography-font-family: Roboto, 'Helvetica Neue', sans-serif;
    --mdc-theme-primary-rgb: 32, 159, 252;
    --mat-option-selected-state-label-text-color: #209ffc;
    --mat-select-focused-arrow-color: #209ffc;
    --mdc-outlined-text-field-focus-outline-color: #209ffc;
  }
}
```

You can access the internal styles of the component with this:
```scss
    ngx-material-intl-tel-input::ng-deep {
      // Your overriding styles here
      .main-label {
        font-weight: bold;
        text-align: right;
      }
      mat-icon {
        svg {
          color: red !important;
        }
      }
    }
```

Just so you know, this component contains two elements from Angular Material: a Select to choose the country and an Input to type the phone number. Keep that in mind for more complex styling.
